(function () {
  if (window.RegDocFormPage) return;
  if (window.getToken && !window.getToken()) return;

  var el = function (id) { return document.getElementById(id); };

  window.RegDocFormPage = {
    apiBaseUrl: window.API_BASE_URL || (window.location.hostname === 'localhost' ? 'http://localhost:8000' : ''),
    fetchApi: window.fetchWithAuth || fetch,
    state: {
      priceList: [],
      selectedDocuments: [],
      historyItems: [],
      historyPage: 0,
      historyPageSize: 5
    },
    el: el,
    inputs: {
      clientFio: el('clientFio'),
      clientBirthDate: el('clientBirthDate'),
      clientBirthPlace: el('clientBirthPlace'),
      clientPassportSeries: el('clientPassportSeries'),
      clientPassportNumber: el('clientPassportNumber'),
      clientPassportIssuedBy: el('clientPassportIssuedBy'),
      clientPassportIssuedDate: el('clientPassportIssuedDate'),
      clientPassportDivisionCode: el('clientPassportDivisionCode'),
      clientAddress: el('clientAddress'),
      clientPhone: el('clientPhone'),
      clientIsLegal: el('clientIsLegal'),
      clientLegalName: el('clientLegalName'),
      clientInn: el('clientInn'),
      clientOgrn: el('clientOgrn'),
      hasSeller: el('hasSeller'),
      sellerFio: el('sellerFio'),
      sellerBirthDate: el('sellerBirthDate'),
      sellerPassportSeries: el('sellerPassportSeries'),
      sellerPassportNumber: el('sellerPassportNumber'),
      sellerPassportIssuedBy: el('sellerPassportIssuedBy'),
      sellerPassportIssuedDate: el('sellerPassportIssuedDate'),
      sellerPassportDivisionCode: el('sellerPassportDivisionCode'),
      sellerAddress: el('sellerAddress'),
      hasTrustee: el('hasTrustee'),
      trusteeFio: el('trusteeFio'),
      trusteeBirthDate: el('trusteeBirthDate'),
      trusteePassportSeries: el('trusteePassportSeries'),
      trusteePassportNumber: el('trusteePassportNumber'),
      trusteePassportIssuedBy: el('trusteePassportIssuedBy'),
      trusteePassportIssuedDate: el('trusteePassportIssuedDate'),
      trusteePassportDivisionCode: el('trusteePassportDivisionCode'),
      vin: el('vin'),
      brandModel: el('brandModel'),
      vehicleType: el('vehicleType'),
      year: el('year'),
      engine: el('engine'),
      chassis: el('chassis'),
      body: el('body'),
      color: el('color'),
      srtsSeries: el('srtsSeries'),
      srtsNumber: el('srtsNumber'),
      srtsIssuedBy: el('srtsIssuedBy'),
      srtsIssuedDate: el('srtsIssuedDate'),
      plateNumber: el('plateNumber'),
      ptsSeries: el('ptsSeries'),
      ptsNumber: el('ptsNumber'),
      ptsIssuedBy: el('ptsIssuedBy'),
      ptsIssuedDate: el('ptsIssuedDate'),
      dkpDate: el('dkpDate'),
      summaDkp: el('summaDkp'),
      dkpNumber: el('dkpNumber'),
      dkpSummary: el('dkpSummary'),
      stateDuty: el('stateDuty'),
      needPlate: el('needPlate'),
      plateQuantity: el('plateQuantity')
    },
    docSelect: el('docSelect'),
    btnAddDoc: el('btnAddDoc'),
    documentsList: el('documentsList'),
    documentsEmpty: el('documentsEmpty'),
    historyTrigger: el('historyTrigger'),
    historyPopover: el('historyPopover'),
    historyRange: el('historyRange'),
    historyPrev: el('historyPrev'),
    historyNext: el('historyNext'),
    formHistoryList: el('formHistoryList'),
    formHistoryLoading: el('formHistoryLoading'),
    summary: {
      sumStateDuty: el('sumStateDuty'),
      sumIncome: el('sumIncome'),
      sumPlate: el('sumPlate'),
      sumPlateRow: el('sumPlateRow'),
      sumTotal: el('sumTotal')
    },
    preview: {
      previewFio: el('previewFio'),
      previewPassport: el('previewPassport'),
      previewAddress: el('previewAddress'),
      previewPhone: el('previewPhone'),
      previewSeller: el('previewSeller'),
      previewTrustee: el('previewTrustee'),
      previewVehicle: el('previewVehicle'),
      previewDkp: el('previewDkp'),
      previewService: el('previewService'),
      previewTotal: el('previewTotal')
    },
    btnAcceptCash: el('btnAcceptCash'),
    btnPrint: el('btnPrint'),
    orderIdDisplay: el('orderIdDisplay'),
    currentTime: el('currentTime')
  };
})();
